module.exports = {
  mySidebar: [
    "intro",
    "howShouldIReadThisBook",
    "reactChangelog",
    {
      type: "category",
      label: "مقدمه",
      items: [
        {
          type: "autogenerated",
          dirName: "0.welcomeToReact", // generate sidebar slice from docs/api (or versioned_docs/version/api)
        },
      ],
    },
    {
      type: "category",
      label: "فصل اول. مفاهیم ابتدایی",
      items: [
        {
          type: "autogenerated",
          dirName: "1.basicConcepts", // generate sidebar slice from docs/api (or versioned_docs/version/api)
        },
      ],
    },
    {
      type: "category",
      label: "فصل دوم. مفاهیم پیشرفته",
      items: [
        {
          type: "autogenerated",
          dirName: "2.AdvancedConcepts", // generate sidebar slice from docs/api (or versioned_docs/version/api)
        },
      ],
    },
    {
      type: "category",
      label: "فصل سه. استایل دهی",
      items: [
        {
          type: "autogenerated",
          dirName: "3.Styling", // generate sidebar slice from docs/api (or versioned_docs/version/api)
        },
      ],
    },
    {
      type: "category",
      label: "فصل چهارم. فرم",
      items: [
        {
          type: "autogenerated",
          dirName: "4.Forms", // generate sidebar slice from docs/api (or versioned_docs/version/api)
        },
      ],
    },
    {
      type: "category",
      label: "فصل پنجم. مدیریت state",
      items: [
        {
          type: "autogenerated",
          dirName: "5.stateMangement", // generate sidebar slice from docs/api (or versioned_docs/version/api)
        },
      ],
    },
    {
      type: "category",
      label: "فصل ششم. ارتباط با سرور",
      items: [
        {
          type: "autogenerated",
          dirName: "6.communicatingWithServer", // generate sidebar slice from docs/api (or versioned_docs/version/api)
        },
      ],
    },
    {
      type: "category",
      label: "فصل هفتم. تست",
      items: [
        {
          type: "autogenerated",
          dirName: "7.test", // generate sidebar slice from docs/api (or versioned_docs/version/api)
        },
      ],
    },
    {
      type: "category",
      label: "فصل هشتم. بهینگی",
      items: [
        {
          type: "autogenerated",
          dirName: "8.optimization", // generate sidebar slice from docs/api (or versioned_docs/version/api)
        },
      ],
    },
    {
      type: "category",
      label: "فصل نهم. نکات و best practice ها",
      items: [
        {
          type: "autogenerated",
          dirName: "9.bestParctice", // generate sidebar slice from docs/api (or versioned_docs/version/api)
        },
      ],
    },
  ],
};
